name: RevMate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  firebase_core_web: ^2.17.2
  flutter_tesseract_ocr: ^0.4.27
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  image: ^4.2.0
  flutter_local_notifications: ^17.2.2
  permission_handler:  ^11.3.1


  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_database: ^11.0.1
  firebase_analytics: ^11.3.0
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.2.0
  cloud_functions: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/makerlandlogo.png
    - assets/equipment_1.png
    - assets/equipment_2.png
    - assets/equipment_3.png
    - assets/equipment_4.png
    - assets/equipment_5.png
    - assets/equipment_6.png
    - assets/equipment_7.png
    - assets/equipment_8.png
    - assets/equipment_9.png
    - assets/equipment_10.png
    - assets/equipment_11.png
    - assets/equipment_12.png
    - assets/equipment_13.png
    - assets/equipment_14.png
    - assets/equipment_15.png
    - assets/status_icon.png
    - assets/reserve_icon.png
    - assets/cancel_icon.png
    - assets/tessdata_config.json
    - assets/tessdata/eng.traineddata
    - assets/tessdata/kor.traineddata
    - assets/reivese_icon.png
    - assets/available_icon.png
    - assets/deadline_icon.png
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
