// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSPz9Vq73PhIde8MR1h_opiOTJ5vdjcBA',
    appId: '1:685883143487:android:bb0fb5ed5475712caf0f8a',
    messagingSenderId: '685883143487',
    projectId: 'revmate-c8170',
    storageBucket: 'revmate-c8170.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ_Sxs_rczGOK8UViqwMMFcCcU0Nciw5o',
    appId: '1:685883143487:ios:3b2cf0909e68b820af0f8a',
    messagingSenderId: '685883143487',
    projectId: 'revmate-c8170',
    storageBucket: 'revmate-c8170.appspot.com',
    iosBundleId: 'com.example.dummy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPkocQXgyoSrZFo5OmnCHiyJlE1xvna0Y',
    appId: '1:685883143487:web:4638bcabb6014712af0f8a',
    messagingSenderId: '685883143487',
    projectId: 'revmate-c8170',
    authDomain: 'revmate-c8170.firebaseapp.com',
    storageBucket: 'revmate-c8170.appspot.com',
  );
}
